esphome:

rp2040:
  board: rpipicow

# Enable logging
logger:

uart:
  tx_pin: GPIO4
  rx_pin: GPIO5
  baud_rate: 115200
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      delimiter: "\n"
    sequence:
      - lambda: |-
          UARTDebug::log_string(direction, bytes);
          int powState=0;
          int dimState=0;
          std::string str(bytes.begin(), bytes.end());
          if (sscanf(str.c_str(), "OK %d,%d", &powState, &dimState) == 2 ) {
            id(switch1).publish_state(powState);
          }

switch:
  - platform: uart
    id: switch1
    name: $friendly_name
    data:
      turn_on: "\rPOW 1\r"
      turn_off: "\rPOW 0\r"
