esphome:
  name: elko-gled316-02
  friendly_name: elko-gled316-02
  on_boot:
    then:
      uart.write: "\rSTA\r"

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  baud_rate: 0

wifi:
  id: wificomp
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      delimiter: "\r"
    sequence:
      - lambda: |-
          //UARTDebug::log_string(direction, bytes);

          // direction: 1 - send, 0 - receive
          if (direction == 0) {
            int powState=0;
            int dimState=0;
            std::string str(bytes.begin(), bytes.end());

            if (sscanf(str.c_str(), "OK %d,%d\r", &powState, &dimState) == 2) {
              id(elko_switch).publish_state(powState);
            }

            if (str.find("RES\r") != std::string::npos) {
              ESP_LOGD("uart", "Restart");
              delay(5000);
              id(switch_restart).turn_on();
            }

            if (str.find("LRN\r") != std::string::npos) {
              ESP_LOGD("uart", "AP mode");
              delay(5000);
              id(activate_wifi_fallback).execute();
            }
          }

script:
  - id: activate_wifi_fallback
    mode: restart
    then:
      - lambda: |-
          id(wificomp).set_ap_timeout(1);
          id(wificomp).disable();
          id(wificomp).clear_sta();
          id(wificomp).enable();
      - delay: 600s
      - switch.turn_on: switch_restart

switch:
  - platform: uart
    id: elko_switch
    name: "Test switch 1"
    data:
      turn_on: "POW 1\n"
      turn_off: "POW 0\n"
  - platform: restart
    id: switch_restart
    internal: True